import Profile from "./parag2.jpg";

export const Topbidsdata = [
  {
    title: "Parag Thakre",
    url: "#",
    image: Profile,
    eth: "100 Crore",
    cName: "nav-links",
  },
  {
    title: "Parag Thakre",
    url: "#",
    image: Profile,
    eth: "100 Crore",
    cName: "nav-links",
  },
  {
    title: "Parag Thakre",
    url: "#",
    image: Profile,
    eth: "100 Crore",
    cName: "nav-links",
  },
  {
    title: "Parag Thakre",
    url: "#",
    image: Profile,
    eth: "100 Crore",
    cName: "nav-links",
  },
  {
    title: "Parag Thakre",
    url: "#",
    image: Profile,
    eth: "100 Crore",
    cName: "nav-links",
  },
  {
    title: "Parag Thakre",
    url: "#",
    image: Profile,
    eth: "100 Crore",
    cName: "nav-links",
  },
  {
    title: "Parag Thakre",
    url: "#",
    image: Profile,
    eth: "100 Crore",
    cName: "nav-links",
  },
  {
    title: "Parag Thakre",
    url: "#",
    image: Profile,
    eth: "100 Crore",
    cName: "nav-links",
  },
  {
    title: "Parag Thakre",
    url: "#",
    image: Profile,
    eth: "100 Crore",
    cName: "nav-links",
  },
  {
    title: "Parag Thakre",
    url: "#",
    image: Profile,
    eth: "100 Crore",
    cName: "nav-links",
  },
  {
    title: "Parag Thakre",
    url: "#",
    image: Profile,
    eth: "100 Crore",
    cName: "nav-links",
  },
  {
    title: "Parag Thakre",
    url: "#",
    image: Profile,
    eth: "100 Crore",
    cName: "nav-links",
  },
  {
    title: "Parag Thakre",
    url: "#",
    image: Profile,
    eth: "100 Crore",
    cName: "nav-links",
  },
  {
    title: "Parag Thakre",
    url: "#",
    image: Profile,
    eth: "100 Crore",
    cName: "nav-links",
  },
  {
    title: "Parag Thakre",
    url: "#",
    image: Profile,
    eth: "100 Crore",
    cName: "nav-links",
  },
  {
    title: "Parag Thakre",
    url: "#",
    image: Profile,
    eth: "100 Crore",
    cName: "nav-links",
  },
];
